import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Noah's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/css.gg@2.0.0/icons/css/check-r.css"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
